WebApplication1/Models/Ilan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class Ilan
    {
        [Key]
        public int IlanID { get; set; }
        public string IlanAciklama { get; set; }

        [DataType(DataType.Date)]
        [Column(TypeName = "Date")]
        public DateTime IlanBaslangicTarihi { get; set; }

        [DataType(DataType.Date)]
        [Column(TypeName = "Date")]
        public DateTime IlanBitisTarihi { get; set; }

        public bool IlanAktifMi { get; set; }             
    }
}

WebApplication1/Controllers/IlanController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Controllers.Filter;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [UserFilter]
    public class IlanController : Controller
    {
        private readonly Context _context;
        public IlanController(Context context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult IlanGoster()
        {
            var degerler = _context.Ilans.ToList();
            return View(degerler);
        }
        [HttpGet]
        public IActionResult YeniIlan()
        {
            return View();
        }
        [HttpPost]
        public IActionResult YeniIlan(Ilan i)
        {
            _context.Ilans.Add(i);
            _context.SaveChanges();
            return RedirectToAction("IlanGoster");
        }
        public IActionResult IlanSil(int id)
        {
            var dep = _context.Ilans.Find(id);
            _context.Ilans.Remove(dep);
            _context.SaveChanges();
            return RedirectToAction("IlanGoster");
        }
        public IActionResult IlanGetir(int id)
        {
            var ilan = _context.Ilans.Find(id);
            return View(ilan);
        }
        public IActionResult IlanGuncelle(Ilan i)
        {
            var change = _context.Ilans.Find(i.IlanID);
            change.IlanAciklama = i.IlanAciklama;
            change.IlanAktifMi = i.IlanAktifMi;
            change.IlanBaslangicTarihi = i.IlanBaslangicTarihi;
            change.IlanBitisTarihi = i.IlanBitisTarihi;          
            _context.SaveChanges();
            return RedirectToAction("IlanGoster");
        }
    }
}

WebApplication1/Views/Ilan/IlanGetir.cshtml
@model WebApplication1.Models.Ilan
@{
    ViewData["Title"] = "IlanGetir";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<h2>İlan Güncelle</h2>
<br />
@using (Html.BeginForm("IlanGuncelle", "Ilan", FormMethod.Post))
{
    @Html.HiddenFor(x => x.IlanID)
    <b>Ilan Aciklama</b>
    @Html.TextBoxFor(x => x.IlanAciklama, new { @class = "form-control", @required = "required" })
    <br />
    <b>İlan Başlangıç Tarihi</b>
    <br />
    @Html.EditorFor(x => x.IlanBaslangicTarihi, "{0:dd.MM.yyyy}", new { @id = "IlanBaslangicTarihi", @type = "date", @required = "required" })
    <br />
    <br />
    <b>İlan Bitiş Tarihi</b>
    <br />
    @Html.EditorFor(x => x.IlanBitisTarihi, "{0:dd.MM.yyyy}", new { @id = "IlanBitisTarihi", @type = "date", @required = "required" })
    <br />
    <br />
    <label>İlan Aktif Mi</label>
    <br />
    @Html.DropDownList("İlan Aktif Mi", new List<SelectListItem>
    {
          new SelectListItem { Text = "Evet", Value = "True"},
          new SelectListItem { Text = "Hayır", Value = "False"}
    },"Seçiniz", new { @required = "required" })
    <br />
    <br />
    <button class="btn btn-info">İlan Güncelle</button>
}

WebApplication1/Views/Ilan/IlanGoster.cshtml
@using WebApplication1.Models
@model List<Ilan>
@{
    ViewData["Title"] = "IlanGoster";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<h2>İlanlar</h2>
<br />
<table id="table1" class="table table-bordered">
    <thead>
        <tr>
            <th>İlan Açıklaması</th>
            <th>İlan Başlangıç</th>
            <th>İlan Bitiş</th>
            <th>İlan Aktif Mi</th>
            <th>Güncelle</th>
            <th>Sil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.IlanAciklama</td>
                <td>@x.IlanBaslangicTarihi.ToShortDateString()</td>
                <td>@x.IlanBitisTarihi.ToShortDateString()</td>
                <td>@x.IlanAktifMi</td>
                <td><a href="/Ilan/IlanGetir/@x.IlanID" class="btn btn-success">Güncelle</a></td>
                <td><a href="/Ilan/IlanSil/@x.IlanID" class="btn btn-danger">Sil</a></td>
            </tr>
        }
    </tbody>   
</table>

WebApplication1/Views/Ilan/YeniIlan.cshtml
@model WebApplication1.Models.Ilan
@{
    ViewData["Title"] = "YeniIlan";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<h2>İlan Ekle</h2>
<br />
<form class="form-group" method="post">
    <b>Ilan Aciklama</b>
    @Html.TextBoxFor(x => x.IlanAciklama, new { @class = "form-control", @required = "required" })
    <br />
    <label for="birthdaytime">Başlangıç Tarihi:</label>
    <br />
    <input id="datetime" type="date" name="IlanBaslangicTarihi" required>
    <br />
    <br />
    <label for="birthdaytime">Bitiş Tarihi:</label>
    <br />
    <input id="datetime" type="date" name="IlanBitisTarihi"required>
    <input name="IlanAktifMi" value="True" type="hidden" />
    <br />
    <br />
    <button class="btn btn-info" type="submit">İlan Ekle</button>
</form>